name: myapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  webview_flutter: ^4.0.7
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/hotcig_r234.jpg
    - assets/images/qr_code.png
    - assets/images/checklist.png
    - assets/images/gambar1.png
    - assets/images/gambar2.png
    - assets/images/logo2.png
    - assets/images/promo.jpg
    - assets/images/trml_t200.jpg
    - assets/images/centaurus_m200.jpg
    - assets/images/hexom_v3.jpg
    - assets/images/liq1.jpeg
    - assets/images/liq2.jpg
    - assets/images/ato1.jpg
    - assets/images/ato2.jpg
    - assets/images/bat1.jpg
    - assets/images/bat2.jpg
    
    